export * from "./GenrePage"
export * from "./GenreIdPage"
export * from "./PopularPage"
export * from "./HomePage"
export * from "./TopPage"
export * from  "./MovieDetailsPage"
export * from "./UpcomingPage"
export * from "./SearchPage"